export const rows = [
  {
    id: 1,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
    email: "peterisiaaih@gmail.com",
    status: "active",
    transaction: "#120",
  },
  {
    id: 2,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
    email: "peterisiaaih@gmail.com",
    status: "active",
    transaction: "#120",
  },
  {
    id: 3,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
    email: "peterisiaaih@gmail.com",
    status: "active",
    transaction: "#120",
  },
  {
    id: 4,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
    email: "peterisiaaih@gmail.com",
    status: "active",
    transaction: "#120",
  },
  {
    id: 5,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
    email: "peterisiaaih@gmail.com",
    status: "active",
    transaction: "#120",
  },
  {
    id: 6,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
    email: "peterisiaaih@gmail.com",
    status: "active",
    transaction: "#120",
  },
  {
    id: 7,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
    email: "peterisiaaih@gmail.com",
    status: "active",
    transaction: "#120",
  },
  {
    id: 8,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
    email: "peterisiaaih@gmail.com",
    status: "active",
    transaction: "#120",
  },
  {
    id: 9,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
    email: "peterisiaaih@gmail.com",
    status: "active",
    transaction: "#120",
  },
  {
    id: 10,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
    email: "peterisiaaih@gmail.com",
    status: "active",
    transaction: "#120",
  },
  {
    id: 11,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
    email: "peterisiaaih@gmail.com",
    status: "active",
    transaction: "#120",
  },
  {
    id: 12,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
    email: "peterisiaaih@gmail.com",
    status: "active",
    transaction: "#120",
  },
  {
    id: 13,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
    email: "peterisiaaih@gmail.com",
    status: "active",
    transaction: "#120",
  },
  {
    id: 14,
    username: "Jon Snow",
    avatar:
      "https://images.pexels.com/photos/2983464/pexels-photo-2983464.jpeg",
    email: "peterisiaaih@gmail.com",
    status: "active",
    transaction: "#120",
  },
];

export const productRows = [
  {
    id: 1,
    name: "Apple air pod",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg",
    stock: 123,
    status: "active",
    price: "#60",
  },
  {
    id: 2,
    name: "Apple air pod",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg",
    stock: 123,
    status: "active",
    price: "#60",
  },
  {
    id: 3,
    name: "Apple air pod",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg",
    stock: 123,
    status: "active",
    price: "#60",
  },
  {
    id: 4,
    name: "Apple air pod",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg",
    stock: 123,
    status: "active",
    price: "#60",
  },
  {
    id: 5,
    name: "Apple air pod",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg",
    stock: 123,
    status: "active",
    price: "#60",
  },
  {
    id: 6,
    name: "Apple air pod",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg",
    stock: 123,
    status: "active",
    price: "#60",
  },
  {
    id: 7,
    name: "Apple air pod",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg",
    stock: 123,
    status: "active",
    price: "#60",
  },
  {
    id: 8,
    name: "Apple air pod",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg",
    stock: 123,
    status: "active",
    price: "#60",
  },
  {
    id: 9,
    name: "Apple air pod",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg",
    stock: 123,
    status: "active",
    price: "#60",
  },
  {
    id: 10,
    name: "Apple air pod",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg",
    stock: 123,
    status: "active",
    price: "#60",
  },
  {
    id: 11,
    name: "Apple air pod",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg",
    stock: 123,
    status: "active",
    price: "#60",
  },
  {
    id: 12,
    name: "Apple air pod",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg",
    stock: 123,
    status: "active",
    price: "#60",
  },
  {
    id: 13,
    name: "Apple air pod",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg",
    stock: 123,
    status: "active",
    price: "#60",
  },
  {
    id: 14,
    name: "Apple air pod",
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg",
    stock: 123,
    status: "active",
    price: "#60",
  },
];
